name:                advent
version:             0.1.0.0
github:              "kajigor/advent"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2019 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/advent#readme>

dependencies:
- base >= 4.7 && < 5
- ghc 
- containers

library:
  exposed-modules: 
      Adv01
    , Adv02
    , Adv03
    , Adv04
    , Adv05
  other-modules: []  
  source-dirs: src
  dependencies: 
    - base >=4.7 && <5

executables:
  advent-01:
    main:                Main.hs
    source-dirs:         app/01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
  advent-02:
    main:                Main.hs
    source-dirs:         app/02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
  advent-03:
    main:                Main.hs
    source-dirs:         app/03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
  advent-04:
    main:                Main.hs
    source-dirs:         app/04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
  advent-05:
    main:                Main.hs
    source-dirs:         app/05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent


tests:
  advent-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
    - hedgehog
    - HUnit
    - tasty
    - tasty-hedgehog
    - tasty-hunit
